version: "3.9"

services:
  web:
    image: python:3.11
    container_name: my-web-app
    working_dir: /app
    volumes:
      - .:/app
    command: python app.py
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: my-postgres-db
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student123
      POSTGRES_DB: myappdb
    ports:
      - "5432:5432"